version: '3'
services:
  node-app:
    build:
      context: .
      target: development 
    volumes:
      - F:\DevOps\Docker\node-app\src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev